
name: terraform_pipeline_infy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  deployments: write

jobs:
  stage-plan:
    runs-on: ubuntu-latest  #arc-runner-setvalue

    steps:
      # checkout (already present)
      - uses: actions/checkout@v4
      
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.REPO_AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.REPO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REPO_AZURE_SUBSCRIPTION_ID }}


  stage-apply:
    runs-on: ubuntu-latest
    needs: [ stage-plan ]
    environment: test
    if: github.ref == 'refs/heads/main' # Only run apply on main branch

    steps:
      # checkout (already present)
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.TEST_AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST_AZURE_SUBSCRIPTION_ID }}